### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by Blueberryy**
Will be doing translation of manual and other files in future.

### CODE REVIEW

**Comment by MouriNaruto** [comment]
@Blueberryy

I am curious that why not translate `Source/Native/NSudoLauncher/Resources/ru/CommandLineHelp.txt`.

It looks still written in English.

Kenji Mouri

**Comment by Blueberryy** [comment]
> @Blueberryy
> 
> I am curious that why not translate `Source/Native/NSudoLauncher/Resources/ru/CommandLineHelp.txt`.
> 
> It looks still written in English.
> 
> Kenji Mouri

I counted this as _other files_ and i can do it soon if you need

**Comment by MouriNaruto** [comment]
@Blueberryy 

The `Source/Native/NSudoLauncher/Resources/ru/CommandLineHelp.txt` is command line help language resource in NSudo. And I notice you have translated `Source/Native/NSudoLauncher/Resources/ru/Links.txt` and the same command line help content in `Website/ru-ru/docs/Readme.md`. So this is why I am curious about.

Kenji Mouri

**Comment by Blueberryy** [comment]
here

**Comment by MouriNaruto** [comment]
Thank you very much.

**Pull request merged**
